name: Code Formatting

on:
  pull_request:

jobs:
  call-salecheck-formatting:
    uses: SaleCheck/sale-check/.github/workflows/formatting-linting-on-pr.yml@main
    with:
      working-directory: '.'