name: Run Tests using `npm test` on PR to `main`

on:
  pull_request:
    branches:
      - main

jobs:
  call-salecheck-npm-test:
    uses: SaleCheck/sale-check/.github/workflows/npm-test-on-pr.yml@main
    with:
      working-directory: '.'
    secrets: inherit