name: Security Scan for CVEs

on:
  pull_request:
    branches:
      - main

jobs:
  call-salecheck-npm-audit:
    uses: SaleCheck/sale-check/.github/workflows/npm-audit-on-pr.yml@main
    with:
      working-directory: '.'