name: Security Scan for Leaked Secrets

on:
  pull_request:
    branches:
      - main

jobs:
  call-salecheck-secrets-scan:
    uses: SaleCheck/sale-check/.github/workflows/secrets-scan-on-pr.yml@main
